services:
  - type: web
    name: slowapi
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m